### PR TITLE
Automatically disconnect the GoCardless account and display a reconnect notice when the token becomes invalid or inactive.

### LINKED ISSUE #92: Disconnect the GoCardless account and display a notice to the merchant to reconnect if the token becomes inactive
### Describe the Bug
GoCardless invalidates the token when the same GoCardless account is connected to the same app on another site. In that case, the site with the invalid/inactive token still shows the connection as active. The plugin continues calling the GoCardless API, which results in a 401 error. Similarly, the GoCardless payment gateway still appears as an available payment method on the checkout page, and whenever a customer tries to place an order, it fails.

To resolve this, we need to disconnect the account whenever the token becomes invalid and inform the merchant about the error, either by showing a notice on the dashboard or by sending an email notification explaining the token invalidation.

### To Reproduce
1. Connect a GoCardless account on one site.
2. Make sure it works as expected.
3. Connect the same GoCardless account on a different site (this will invalidate the token on the first site).
4. Go to the first site and try to place an order. Notice that the order fails due to a token error.

### Screenshots

Image

### Expected Behavior
The merchant should be informed when a token becomes inactive/invalid, and the GoCardless payment method should not appear in the list of available payment methods if the token is not active.

### Actual Behavior
The GoCardless payment method is still displayed on the checkout page even after the token becomes inactive.

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

### PR DESCRIPTION
**Pull request by iamdharmesh**
### All Submissions:

* [x] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:
As reported in #92, if the GoCardless access token becomes invalid or inactive, there is currently no mechanism to disconnect the GoCardless account or make the gateway unavailable to prevent order placement failures. This results in orders failing with the error described in the issue. Additionally, due to the failed API responses, the “get available schemes (/creditors)” API response is not cached, causing repeated 401 calls for it.

This PR introduces changes to automatically disconnect the GoCardless account and display a notice prompting the admin to reconnect the account when the token becomes invalid or inactive (technically, when the API responds with a 401). This ensures that the GoCardless payment method is no longer visible at checkout and that no unnecessary calls to the creditors API are made. An admin notice will clearly inform the site owner to reconnect the account in order to restore the payment gateway functionality.

image

> [!NOTE]
> In addition to showing a notice in the admin, we could also send an email to the site admin to reconnect the account. However, for now, showing the notice in the admin should be sufficient. If we receive requests from merchants, we can add the email notification later.

Closes #92

### Steps to test the changes in this Pull Request:
1. Connect a GoCardless account on one site.
2. Verify that it works as expected.
3. Connect the same GoCardless account on a different site (this will invalidate the token on the first site).
4. On the first site, attempt to place an order. Notice that the order fails due to a token error.
5. Refresh the page and confirm that the GoCardless payment gateway is no longer available.
6. In wp-admin, verify that a notice is displayed prompting you to reconnect the GoCardless account.
7. Go to the GoCardless payment method settings page, enable logging, and refresh the settings page multiple times.
8. Go to `WooCommerce > Status > Logs`, open the GoCardless logs, and confirm that there are no repeated `/creditors` API calls with 401 failures.
9. Reconnect the GoCardless account and confirm that everything works as expected.

### CODE REVIEW

File: includes/class-wc-gocardless-order-admin.php [hunk 1]
```diff
@@ -576,4 +577,43 @@ public function get_connection_notice() {
...
+		// Check if option is set to display notice.
+		if ( ! get_option( 'wc_gocardless_access_token_unauthorized' ) ) {
+			return;
+		}
+
+		// Check if access token is there.
+		$settings = get_option( 'woocommerce_gocardless_settings', array() );
+		if ( ! empty( $settings['access_token'] ) ) {
+			return;
+		}
```
Comment (dkotter) [inline includes/class-wc-gocardless-order-admin.php:598]: Wondering if in this scenario (the `wc_gocardless_access_token_unauthorized` option exists but we still have an access token), should we delete the `wc_gocardless_access_token_unauthorized` option?

Comment (iamdharmesh) [reply includes/class-wc-gocardless-order-admin.php:598]: Good point! Addressed in https://github.com/gocardless/woocommerce-gateway-gocardless/pull/94/commits/eb10d4d91898db8522b6536f4e63c59a7661fa1a

**Review by dkotter — DISMISSED** [review]
Code looks good to me, noting though that E2E tests seem to be failing

**Review by qasumitbagthariya — DISMISSED** [review]
### QA Update  ✅ 
-------------

I have verified this PR in the `fix/92` branch, which has been fixed and is functioning as intended.

I tested the following on this branch:
	•	Connected the same account on Site B → token on Site A got invalidated as expected.
	•	On Site A, placing an order failed with a token error.
	•	After refreshing, GoCardless gateway was no longer available.
•     Verified in wp-admin: a reconnect notice was displayed.
	•	Reconnected GoCardless account → confirmed everything works as expected.




**Testing Environment** 

<Details>

- WordPress: 6.8.2
- Theme: Twenty Twenty-Five 1.3
- WooCommerce - 10.2.0
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: fix/92

</Details>


Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for UAT
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [x] Yes
- [ ] Not Required/Applicable for this PR
------------------------------------------------

**Review by jeffpaul — DISMISSED** [review]

**Comment by iamdharmesh** [comment]
Note: I just made some changes to fix failing E2E tests which has dismissed reviews. but we are good to go here.

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.8.4, npm version 10.8.2, node version 20.18.1)

**Testing Environment** 

<Details>

- WordPress: 6.8.3
- Theme: Twenty Twenty-Five 1.3
- WooCommerce - 10.2.2
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: fix/92

</Details>

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.


Next Step- Ready to Merge 🚀
