### PR TITLE
Fix inconsistent subscription status after cancellation with centralized cancellation logic

### LINKED ISSUE #78: Inconsistent subscription status display after cancellation
### Describe the Bug

After cancelling a subscription, the status is not consistent across different areas.

### To Reproduce

1. Checkout with a subscription product.
2. Cancel the subscription (either from frontend or backend).

### Screenshots

https://github.com/user-attachments/assets/04766d41-ea20-4afa-9002-8c6337f69a58

### Expected Behavior

All sections (Orders, Subscriptions, both frontend and backend) should consistently reflect the "cancelled" status after the subscription is cancelled.

### Actual Behavior

1. Backend Orders section shows status as "pending subscription".
2. My Account > Subscriptions also shows "pending subscription".
3. But My Account > Orders shows status as "cancelled".

### Environment

 - WordPress Version 6.8.2
 - WooCommerce Version 10.0.3
 - Plugin Version 
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

### PR DESCRIPTION
**Pull request by lmcrean**
## Problem Statement

When users cancel subscriptions before GoCardless payment is confirmed (2-7 day window), the status incorrectly shows "Pending Cancellation" instead of "Cancelled". This creates confusion as the payment hasn't been confirmed yet.

## Root Cause

Two issues:
1. Missing status synchronization between parent orders and subscriptions
2. No check for payment confirmation status during user-initiated cancellations

### 1. Centralized Cancellation Handling
- Added `handle_subscription_cancellation()` method in `class-wc-gocardless-gateway.php`
- Handles webhook-based cancellations (payment/billing request cancelled)
- Clears pending payment metadata consistently

### 2. Parent Order Status Sync
- Added `sync_parent_order_status()` in `class-wc-gocardless-gateway-addons.php`
- Updates parent order to "cancelled" when all subscriptions are cancelled
- Ensures status consistency across orders and subscriptions

### 3. User-Initiated Cancellation with Payment Check
- Added `maybe_skip_pending_cancel_status()` filter callback
- Checks parent order's `_gocardless_payment_status` meta
- Skips pending-cancel if payment not confirmed/paid_out
- Forces immediate cancellation for unconfirmed payments

## Expected Behavior

| Scenario | Payment Status | User Cancels → Result |
|----------|----------------|----------------------|
| Payment confirmed | `confirmed` / `paid_out` | Pending Cancellation ✓ |
| Payment unconfirmed | `pending_submission` / `submitted` / `pending_customer_approval` | Cancel immediately ✓ |

## Testing

**Manual Test:**
1. Create a subscription order (payment status will be `pending_submission`)
2. User cancels subscription from My Account or wp-admin
3. Verify subscription status = "Cancelled" (not "Pending Cancellation")
4. Verify parent order status = "Cancelled"
5. Check logs for: "Skipping pending-cancel for subscription #X..."

**After Payment Confirmed:**
1. Wait for payment status to update to `confirmed`
2. User cancels subscription
3. Verify subscription status = "Pending Cancellation"

## Files Changed

- `includes/class-wc-gocardless-gateway.php` - Centralized cancellation handler
- `includes/class-wc-gocardless-gateway-addons.php` - Parent sync + payment check filter

## Related

PR #50 (webhook-based cancellation handling)
Fixes #78

### Changelog entry

> Fix - Inconsistent subscription status after cancellation.

### CODE REVIEW

**Comment by lmcrean** [comment]
Confirmed in unit testing, does anyone have access to trying on local machine with the paid subscription plugin? @diegocurbelo  @peterwilsoncc  @joemcgill  @dkotter

File: includes/class-wc-gocardless-gateway-addons.php [hunk 1]
```diff
@@ -33,13 +33,52 @@ public function __construct() {
...
 
 		if ( class_exists( 'WC_Pre_Orders_Order' ) ) {
 			add_action( 'wc_pre_orders_process_pre_order_completion_payment_' . $this->id, array( $this, 'process_payment_for_released_pre_order' ) );
 		}
 	}
 
+	/**
+	 * Synchronize parent order status when all subscriptions are cancelled.
+	 *
+	 * @since 2.9.8
```
Comment (dkotter) [inline includes/class-wc-gocardless-gateway-addons.php]:
```suggestion
	 * @since x.x.x
```

File: includes/class-wc-gocardless-gateway.php [hunk 2]
```diff
@@ -2315,11 +2313,58 @@ protected function _process_billing_request_event_cancelled( array $event ) {
...
 		}
 
 		return true;
 	}
 
+	/**
+	 * Centralized handler for subscription cancellation.
+	 * Ensures consistent status updates across orders and subscriptions.
+	 *
+	 * @since 2.9.8
```
Comment (dkotter) [inline includes/class-wc-gocardless-gateway.php]:
```suggestion
	 * @since x.x.x
```

**Review by dkotter — DISMISSED** [review]

File: includes/class-wc-gocardless-gateway.php [hunk 3]
```diff
@@ -2066,11 +2068,7 @@ protected function _process_subscription_event( array $event ) {
 				$this->_maybe_update_subscriptions_with_mandate( $subscriptions, $subscription_id );
 				break;
 			case 'cancelled':
-				// Only cancel WCS subscriptions when the order missing mandate.
-				$mandate_in_order = $this->get_order_resource( $order_id, 'mandate', 'id' );
-				if ( ! $mandate_in_order && class_exists( 'WC_Subscriptions_Manager' ) ) {
-					WC_Subscriptions_Manager::cancel_subscriptions_for_order( $order_id );
-				}
+				$this->handle_subscription_cancellation( wc_get_order( $order_id ), __( 'Subscription cancelled.', 'woocommerce-gateway-gocardless' ) );
```
Comment (iamdharmesh) [inline includes/class-wc-gocardless-gateway.php]: We are no longer using GoCardless-side subscriptions, and this code is only for backward compatibility. So, no changes are needed here.

**Review by iamdharmesh — CHANGES_REQUESTED** [review]
Thanks a lot for the PR, @lmcrean. While reviewing the PR, I noticed that the issue report(#78) didn’t include the background details and all the necessary information (apologies for that). I’ve added additional context and details about the issue [here](https://github.com/gocardless/woocommerce-gateway-gocardless/issues/78#issuecomment-3359940627).

While testing this PR, I also noticed that it doesn’t fully resolve the issue. Could you please review the additional information I’ve shared and confirm?

Thanks again for your contribution!

File: includes/class-wc-gocardless-gateway.php (hunk 3 above)
Comment (lmcrean) [reply includes/class-wc-gocardless-gateway.php]: Resolved, thank you

**Comment by lmcrean** [comment]
Thanks @iamdharmesh for the context! I can see that the initial PR handled webhook-based cancellations but missed user-initiated cancellations with unconfirmed payments.

So I've added a fix for the missing piece. This completes the behavior described in your summary:
- Payment confirmed → User cancels → Pending Cancellation
- Payment unconfirmed → User cancels → Cancel immediately (now fixed)

Let me know if you'd like me to adjust anything

File: includes/class-wc-gocardless-gateway.php [hunk 4]
```diff
@@ -1921,6 +1921,8 @@ protected function _process_payment_event( array $event ) {
 				break;
 			case 'cancelled':
 				$new_status = 'cancelled';
+				// Centralized cancellation handling
+				$this->handle_subscription_cancellation( $order, __( 'Payment cancelled.', 'woocommerce-gateway-gocardless' ) );
```
Comment (iamdharmesh) [inline includes/class-wc-gocardless-gateway.php]: As we have already handled subscription cancellation for webhook in #50. So, this handling is no longer needed unless anything specific not working here.

File: includes/class-wc-gocardless-gateway-addons.php [hunk 5]
```diff
@@ -33,13 +33,100 @@ public function __construct() {
 			// Cancel in-progress payment on subscription cancellation.
 			add_action( 'woocommerce_subscription_pending-cancel_' . $this->id, array( $this, 'maybe_cancel_subscription_payment' ) );
 			add_action( 'woocommerce_subscription_cancelled_' . $this->id, array( $this, 'maybe_cancel_subscription_payment' ) );
+			
+			// Status synchronization for parent orders
+			add_action( 'woocommerce_subscription_status_updated', array( $this, 'sync_parent_order_status' ), 10, 3 );
+
+			// Skip pending-cancel for subscriptions with unconfirmed payments
+			add_filter( 'woocommerce_subscription_use_pending_cancel', array( $this, 'maybe_skip_pending_cancel_status' ), 10, 2 );
```
Comment (iamdharmesh) [inline includes/class-wc-gocardless-gateway-addons.php]: This filter has only 1 argument and due to that I am getting fatal error. Could you please help to check once?

**Review by iamdharmesh — CHANGES_REQUESTED** [review]
Thanks for the changes @lmcrean. I have added some more comments could you please check it once?

File: includes/class-wc-gocardless-gateway.php (hunk 4 above)
Comment (lmcrean) [reply includes/class-wc-gocardless-gateway.php]: Thanks for the catch. Removed.

File: includes/class-wc-gocardless-gateway-addons.php (hunk 5 above)
Comment (lmcrean) [reply includes/class-wc-gocardless-gateway-addons.php]: Thanks @iamdharmesh for the review.

I've fixed this by:

1. **Removing the problematic filter hook** (includes/class-wc-gocardless-gateway-addons.php #L41)
2. **Removing the `maybe_skip_pending_cancel_status()` method**
3. **Extended `sync_parent_order_status()` instead** - it already receives the subscription object via the `woocommerce_subscription_status_updated` action

Now when a subscription transitions to `pending-cancel`, the method intercepts it, checks the payment status, and immediately cancels if unconfirmed. Same functionality, no fatal error expected.

**Comment by lmcrean** [comment]
thanks @iamdharmesh could i get your review please? Addressed your suggestions

File: includes/class-wc-gocardless-gateway-addons.php [hunk 6]
```diff
@@ -33,13 +33,83 @@ public function __construct() {
...
+	 */
+	public function sync_parent_order_status( $subscription, $new_status, $old_status ) {
+		// Only process GoCardless subscriptions
+		if ( $this->id !== $subscription->get_payment_method() ) {
+			return;
+		}
+
+		// Handle pending-cancel -> cancelled transition for unconfirmed payments
+		if ( 'pending-cancel' === $new_status && 'pending-cancel' !== $old_status ) {
+			$parent_order = $subscription->get_parent();
```
Comment (iamdharmesh) [inline includes/class-wc-gocardless-gateway-addons.php]: Maybe we should consider checking payment status of last order? 🤔 Thinking cases where subscription is getting cancelled after 2-3 renewals.

File: includes/class-wc-gocardless-gateway-addons.php [hunk 7]
```diff
@@ -33,13 +33,83 @@ public function __construct() {
...
+			if ( $parent_order ) {
+				// Check payment confirmation status
+				$payment_status = $parent_order->get_meta( '_gocardless_payment_status', true );
```
Comment (iamdharmesh) [inline includes/class-wc-gocardless-gateway-addons.php]: Maybe we should get payment status from GoCardless directly, to make sure it's latest (to avoid any edge case). what do you think?

File: includes/class-wc-gocardless-gateway-addons.php [hunk 8]
```diff
@@ -33,13 +33,83 @@ public function __construct() {
...
+				return; // Not all cancelled, don't update parent
+			}
+		}
+
+		// All subscriptions cancelled, update parent order
+		$parent_order->update_status(
+			'cancelled',
+			__( 'Order cancelled - all subscriptions have been cancelled.', 'woocommerce-gateway-gocardless' )
+		);
+		$parent_order->delete_meta_data( '_gocardless_payment_pending' );
```
Comment (iamdharmesh) [inline includes/class-wc-gocardless-gateway-addons.php]: I think we are not storing `_gocardless_payment_pending` order meta anywhere, is there any reason to delete this?

File: includes/class-wc-gocardless-gateway.php [hunk 9]
```diff
@@ -2315,11 +2315,58 @@ protected function _process_billing_request_event_cancelled( array $event ) {
 		if ( empty( $payment ) && empty( $mandate ) ) {
 			$order->update_status( 'cancelled', __( 'Billing request cancelled.', 'woocommerce-gateway-gocardless' ) );
 			$this->update_order_resource( $order, 'billing_request', $billing_request );
+			$this->handle_subscription_cancellation( $order, __( 'Billing request cancelled by customer.', 'woocommerce-gateway-gocardless' ) );
```
Comment (iamdharmesh) [inline includes/class-wc-gocardless-gateway.php]: Not sure if this is needed, as subscriptions will get cancelled with payment cancelled webhook call, and order is already cancelled on line no 2316. am I missing anything here? Thanks

**Review by iamdharmesh — CHANGES_REQUESTED** [review]
Thanks a lot for the changes @lmcrean and sorry for the delayed review. I was on vacation, just came back this week. Changes now looks good. However, added some feedback to check. Could you please check it once. Thanks.

File: includes/class-wc-gocardless-gateway-addons.php (hunk 6 above)
Comment (lmcrean) [reply includes/class-wc-gocardless-gateway-addons.php]: Good catch! Changed from `get_parent()` to `get_last_order('all')` with fallback.

File: includes/class-wc-gocardless-gateway-addons.php (hunk 8 above)
Comment (lmcrean) [reply includes/class-wc-gocardless-gateway-addons.php]: Thanks for spotting. Searched the codebase and this metadata is never set anywhere, only deleted. Removed the deletion line.

File: includes/class-wc-gocardless-gateway.php (hunk 9 above)
Comment (lmcrean) [reply includes/class-wc-gocardless-gateway.php]: Correct, WCS should handle subscription cancellation when the order status changes. Removed the entire method and the call to it. Much cleaner now.

File: includes/class-wc-gocardless-gateway-addons.php (hunk 7 above)
Comment (lmcrean) [reply includes/class-wc-gocardless-gateway-addons.php]: I think it's worth doing. 

Might add ~200ms etc. API call during cancellation, but ensures we always have the latest status (avoids webhook delay edge cases). Since this is a user-initiated action and the check is critical (determines if user can undo cancellation), the accuracy is worth the small performance cost.

Implementing API call to get fresh payment status.

**Comment by lmcrean** [comment]
@iamdharmesh thanks as always for the codebase insights. I have addressed all points made; see resolved comments. 

Ready for next review.

**Comment by vikrampm1** [comment]
@iamdharmesh this is back for your re-review when you get a moment.

**Review by iamdharmesh — APPROVED** [review]
Thanks a lot for the PR @lmcrean. I have made some minor changes and this is good to go now.

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.8.4, npm version 10.8.2, node version 20.18.1)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

https://github.com/user-attachments/assets/4bea3c5a-f72b-4fc7-b820-a0fe12d994ba

**Testing Environment** 

<Details>

- WordPress: 6.9
- Theme: Storefront 4.6.2
- Theme: Twenty Twenty-Five 1.4
- WooCommerce - 10.4.0
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: smoke-testing

</Details>

Next Step- Ready to Merge 🚀

**Review by qasumitbagthariya — APPROVED** [review]
